### PR TITLE
Use github action

### LINKED ISSUE #47: migrate from Travis to Github Actions
**Description**
https://www.tomasvotruba.com/blog/2020/01/13/why-is-first-instant-feedback-crucial-to-developers/
https://www.tomasvotruba.com/blog/2020/01/27/switch-travis-to-github-actions-to-reduce-stress/#where-should-we-stay-with-travis-ci

### PR DESCRIPTION
**Pull request by vasilvestre**
| Q             | A
| ------------- | ---
| Bug fix?                      | no
| New feature?                  |  no
| BC breaks?                    |  no
| Fixes issues                  | closes https://github.com/sspooky13/yaml-standards/issues/47
| License                       | MIT

I'm trying to replace travis with same behavior :)

I really want PHP 8.0 so... I want to help with https://github.com/sspooky13/yaml-standards/issues/56#issue-810036613 as well next

### CODE REVIEW

**Comment by sspooky13** [comment]
Hello, I thank you for PR. I appreciate that. Today I won't make it but this weekend I will check this out :)

**Comment by vasilvestre** [comment]
So far, PHP 7.4 fails to install dependencies with highest deps level at Symfony ^4.0.10. I'm trying to open them at "^4.0", lowest deps level should act the same

**Comment by vasilvestre** [comment]
So far, PHP 7.4 failed to install dependencies with highest deps level at Symfony ^4.0.10. 

But Travis avoided composer require operation for windows.. I did the same here using conditional. I'm happy this helps :)

Failures related to this https://github.com/vasilvestre/yaml-standards/actions/runs/692795180/workflow, as 7.3 MacOS were already disabled I disabled it too.

```
strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

/Users/runner/work/yaml-standards/yaml-standards/vendor/symfony/config/Definition/BaseNode.php:502
/Users/runner/work/yaml-standards/yaml-standards/vendor/symfony/config/Definition/BaseNode.php:344
/Users/runner/work/yaml-standards/yaml-standards/vendor/symfony/config/Definition/PrototypedArrayNode.php:277
/Users/runner/work/yaml-standards/yaml-standards/vendor/symfony/config/Definition/BaseNode.php:368
/Users/runner/work/yaml-standards/yaml-standards/vendor/symfony/config/Definition/ArrayNode.php:301
/Users/runner/work/yaml-standards/yaml-standards/vendor/symfony/config/Definition/BaseNode.php:368
/Users/runner/work/yaml-standards/yaml-standards/vendor/symfony/config/Definition/PrototypedArrayNode.php:277
/Users/runner/work/yaml-standards/yaml-standards/vendor/symfony/config/Definition/BaseNode.php:368
/Users/runner/work/yaml-standards/yaml-standards/vendor/symfony/config/Definition/Processor.php:35
/Users/runner/work/yaml-standards/yaml-standards/vendor/symfony/config/Definition/Processor.php:52
/Users/runner/work/yaml-standards/yaml-standards/src/Model/Config/YamlStandardConfigLoader.php:29
/Users/runner/work/yaml-standards/yaml-standards/src/Command/YamlCommand.php:45
/Users/runner/work/yaml-standards/yaml-standards/vendor/symfony/console/Command/Command.php:255
/Users/runner/work/yaml-standards/yaml-standards/vendor/symfony/console/Tester/CommandTester.php:77
/Users/runner/work/yaml-standards/yaml-standards/tests/Command/YamlCommandTest.php:99
```

CI's now green :)

**Review by sspooky13 — APPROVED** [review]
It's working, it's quick...simple, it's great 👍. Thank you 😊

**Comment by vasilvestre** [comment]
> It's working, it's quick...simple, it's great 👍. Thank you 😊

It's nice it worked nice so far ;) Thank you for your reaction time :)

**Pull request merged**
