### PR TITLE
Add PHP 8 support

### PR DESCRIPTION
**Pull request by vasilvestre**
| Q             | A
| ------------- | ---
| Bug fix?                      | no
| New feature?                  | no
| BC breaks?                    | no
| Fixes issues                  | https://github.com/sspooky13/yaml-standards/issues/56
| License                       | MIT

I need PHP 8 support here so here's my attempt

### CODE REVIEW

**Comment by vasilvestre** [comment]
Blocked by https://github.com/FriendsOfSymfony/oauth2-php/pull/124 dependency. The repository seem active, I'm working on it

**Comment by vasilvestre** [comment]
Got to run CI again. Issue is fixed :)

**Comment by sspooky13** [comment]
I am sorry, but build still not ending with success. Coding standards library in usage version doesn't support [Symfony 5](https://github.com/sspooky13/yaml-standards/issues/46) and PHP 8. I don't think they will support this version in near future. So we must wait or do you know about better alternative? 🤔

**Comment by vasilvestre** [comment]
> I am sorry, but build still not ending with success. Coding standards library in usage version doesn't support [Symfony 5](https://github.com/sspooky13/yaml-standards/issues/46) and PHP 8. I don't think they will support this version in near future. So we must wait or do you know about better alternative? 🤔

It wasn't fixed, I switch the PR to Draft status :)

**Comment by vasilvestre** [comment]
I have no time for this anymore so I close it :(

**Pull request closed without merging**
