### PR TITLE
regex for path iterator is simplified

### PR DESCRIPTION
**Pull request by boris-brtan**
| Q             | A
| ------------- | ---
| Bug fix?                      | no
| New feature?                  | no
| BC breaks?                    | no
| Standards and tests pass?     | yes
| Fixes issues                  | -
| License                       | MIT

### CODE REVIEW

**Comment by boris-brtan** [comment]
@sspooky13 please don't include me into CHANGELOG.md as a contributor

**Comment by sspooky13** [comment]
Hello @boris-brtan, thanks for your contribution, but it's not good. 
My regex return full path to file:
```php
Array
(
    [0] => ./.github\stale.yml
    [1] => yml
)
```
and you return only extension:
```php
Array
(
    [0] => .yml
    [1] => yml
)
```
I understand your intention but if you want simplify that regex, he must return full path to finded file.

PS: If you wish not be mentioned in changelog as contributor, i dont have to add you, but even so you will be immortalized in contributors page https://github.com/sspooky13/yaml-standards/graphs/contributors 😄

**Comment by boris-brtan** [comment]
OK man, my wrong, but i didnt know that regexIterator stands for filepaths

**Comment by sspooky13** [comment]
Ok, thanks for your contribution. I merged it already

**Pull request merged**
